### ISSUE TITLE
FRONTEND

### ISSUE THREAD

**Issue by ThiagoTrabach** [labFGV/DOliberto#13]
- [x] ato -> JSON
    
- [x] concatenação de atos
    
- [x] campos: título, responsável, cargo do responsável, secretaria, e o texto

- [x] gerar  .json e fazer POST request #23 (v0.0.1)

- [ ] reordenação de atos (v0.1)

- [ ] upload de tabela CSV (v0.1)

**Comment by odanoburu** [comment]
EDIT: ver comentário abaixo

---

@souzamatheusp cara, oq vc acha de mudar a primeira chave do JSON pra data do DO, ao invés de atos?

```javascript
{"Atos":{"Ato1":{"titulo":"Portaria Nº 394/2017","responsavel":"Thaís dos Santos Lima","cargo_responsavel":"Secretária Municipal de Educação","sec":"Secretaria Municipal de Educação","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nulla tellus, semper quis nunc at, mattis rutrum lacus. Phasellus pellentesque lorem nibh, a dictum neque viverra sed. Vestibulum dictum nunc id elementum interdum. Cras semper commodo lectus nec luctus. In fringilla lorem mattis risus convallis condimentum. Sed at purus ac sapien iaculis vestibulum. Vivamus est massa, ultrices at lobortis a, faucibus vel augue."}}
```
para 

```javascript
{"2017-08-18":{"Ato1":{"titulo":"Portaria Nº 394/2017","responsavel":"Thaís dos Santos Lima","cargo_responsavel":"Secretária Municipal de Educação","sec":"Secretaria Municipal de Educação","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nulla tellus, semper quis nunc at, mattis rutrum lacus. Phasellus pellentesque lorem nibh, a dictum neque viverra sed. Vestibulum dictum nunc id elementum interdum. Cras semper commodo lectus nec luctus. In fringilla lorem mattis risus convallis condimentum. Sed at purus ac sapien iaculis vestibulum. Vivamus est massa, ultrices at lobortis a, faucibus vel augue."}}
```
a gente tinha falado de deixar a data só no título do arquivo, mas já que tem essa chave pra botar, talvez seja uma boa!

**Comment by odanoburu** [comment]
uma dúvida: a interface parece colocar em CamelCase tudo o que vc digita em alguns campos, mas no Json não saiu assim, certo? não é melhor deixar como a pessoa colocar?

**Comment by odanoburu** [comment]
@souzamatheusp , update: esquece o comentário sobre a data: acho que o ideal é termos uma chave separada `date:2017-05-11` e uma chave `issue:44` (pro número da edição do D.O.)

**Comment by odanoburu** [comment]
fechando e substituindo pela #36
