### ISSUE TITLE
DO em PDF

### ISSUE THREAD

**Issue by ThiagoTrabach** [labFGV/DOliberto#15]

**Comment by odanoburu** [comment]
@AliferSales , algumas referências possivelmente úteis:


## latex/lualatex

cara, eu acho que seria sensacional se a gente usasse LuaLaTeX para gerar o PDF. assim a gente poderia ler o TOML diretamente no Lua e fazer o PDF:

- pq LuaLaTeX? https://tex.stackexchange.com/questions/70/what-is-a-simple-example-of-something-you-can-do-with-luatex
- biblioteca lua pra ler TOML: https://github.com/jonstoler/lua-toml (https://tex.stackexchange.com/questions/14361/installing-lua-modules-for-use-in-lualatex)


## templates:

- https://www.overleaf.com/latex/templates/newspaper-slash-news-letter-template/wjxxhkxdjxhw#.WZXTjTCGPVM
- https://www.overleaf.com/latex/templates/senac-poster-with-the-sciposter-package/jzsxddxcvncm#.WZXTLDCGPVM
  esse aqui depende de vc conseguir especificar o tamanho do papel (pq o padrão é muito grande)

**Comment by viguardieiro** [comment]
Será que não valeria mais a pena fazer em Python usando [essa biblioteca](https://github.com/uiri/toml) para ler o TOML e [PyLaTeX](https://github.com/JelteF/PyLaTeX) para gerar o PDF?

**Comment by odanoburu** [comment]
@viguardieiro pode ser! só não podemos confundir o PyLaTeX com o LuaLaTeX. 

o LuaLaTeX é uma nova engine de LaTeX, que já foi escolhida para substituir o pdfTeX usado atualmente. isso quer dizer que o LuaLaTeX consegue fazer muito mais do que só produzir o texto .tex que gera o PDF. também quer dizer que o projeto tem manutenção quase garantida por muitos anos.

o  PyLaTeX parece que simplesmente monta o texto .tex que então é usado pelo pdfTeX para gerar o PDF, e é principalmente desenvolvido por um cara só (ou seja, a manutenção pode não ser reliable).

mas de fato, se o PyLaTeX consegue fazer tudo o que precisamos, talvez ele seja a melhor (e mais simples) opção!

---

olhando aqui o PyLaTeX me parece que pode não ser tão vantajoso assim. podemos conversar pra eu te ajudar no setup do Lua (que é o maior entrave pra começar) e aí vc me diz o que vc prefere. como é vc que vai fazer, vc decide!

mas pq acho que o Lua é melhor e mais fácil?  pq a sintaxe dele é igual a do LaTeX, + poucas funções pra usar código lua. a API da biblioteca TOML do lua deve ser simples (e vc teria de aprender a do python tb), então é só isso que vc tem de aprender. no caso do python vc tem de aprender a API do pylatex tb, que me pareceu bem chatinha...

**Comment by odanoburu** [comment]
#17 closes this
