### ISSUE TITLE
botão para gerar .json e fazer POST request

### ISSUE THREAD

**Issue by odanoburu** [labFGV/DOliberto#23]
we need a button for the user to say that he's finished writing the DO, and that she wants to have it processed as a .pdf. when clicked, the button will POST the .json data to our server, and the server will send the .pdf back.

**Comment by odanoburu** [comment]
maybe we don't need AJAX, after all, as jQuery can do the POST request, and we're already using it https://api.jquery.com/jquery.post/

**Comment by souzamatheusp** [comment]
jQuery.post is a shorthand for AJAX requests.

**Comment by souzamatheusp** [comment]
Implemented, see PR https://github.com/labFGV/DOliberto/pull/25
