### ISSUE TITLE
aspas e LaTeX

### ISSUE THREAD

**Issue by odanoburu** [labFGV/DOliberto#44]
em latex geralmente usamos apóstrofos assim <code>``texto entre aspas"</code>, que são renderizados corretamente no pdf. se usarmos `"texto entre aspas"`, ficamos com esse resultado:

![image](https://user-images.githubusercontent.com/19347395/32995520-bef63430-cd5c-11e7-8967-e21575d6e8d2.png)

mas não podemos pedir pra nossos usuários colocarem as aspas dessa forma. o que fazer ?

**Comment by souzamatheusp** [comment]
Substitui com JS?

**Comment by odanoburu** [comment]
como? tipo, as aspas são diferentes, acabaria que teríamos de identificar se é uma aspa de abertura ou fechamento, e tratar isso em nested cases fica chato..
