### ISSUE TITLE
tornar compilação do pdf + rápida

### ISSUE THREAD

**Issue by harllos** [labFGV/DOliberto#50]
Mudar de XeLateX para LateX? isso tb resolve #44 , parece

**Comment by odanoburu** [comment]
[aqui](https://drive.google.com/open?id=1N6ZLSnHt8jJv5RD2jhSu0XgGZEx8y9Dq) tem dois pdf's feitos a partir do mesmo json, um usando pdflatex, outro xelatex (tendo feito as mudanças necessárias em `doliberto.cls`. o pdflatex é pelo menos duas vezes mais rápido (vale lembrar que o latexmk tem de chamar o compilador mais de uma vez pra fazer o TOC, então na verdade ele vai ser ainda mais rápido), e resolve #44 de quebra. PR em breve.
